version: '3.7'
services:
  # Mongodb service
  mongo_db:
    container_name: automobile_db
    ports:
      - "27012:27017"
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db
  # Node api
  api:
    build: .
    ports:
      - "5000:${PORT}"
    env_file:
      - .env
    depends_on:
      - mongo_db
    restart: always
    image: automobile_server:latest
volumes:
  mongo_data: {}
